### ISSUE TITLE
Operating systems

### ISSUE THREAD

**Issue by kevinkindler** [ASE-Kanak-App/ASE-kanak#18]
Decision: Must
Requirement: The system shall not be dependent on the Operating System of a user.
As a: User
I want: To be able to access the app on all Operating Systems.
So that: So that I don’t have to buy a new device.

Defintion of done:
* The app runs on the operating systems:
 - Microsoft Windows
 - Unix
 - Ubuntu
 - Linux
 - Android
 - macOS

**Comment by IDIVASM** [comment]
Hey kevin , 
nice to meet u 

i have some questions for u 

1.so u want a app / software that can run in all operating systems right ??
2. or u want the pre-existing app to run in all operation system ?
3. or u want a operating system that can run all the apps ?
